version: '3.7'
services:
  efr_requests:
    container_name: ${COMPOSE_PROJECT_NAME:-}efr_requests
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:-}efr_requests.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:-}efr_requests.rule=Host(`${COMPOSE_PROJECT_NAME:-}${DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:-}efr_requests.service=${COMPOSE_PROJECT_NAME:-}efr_requests"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME:-}efr_requests.loadbalancer.server.port=80"
