version: '3.7'
services:
  efr_requests:
    container_name: efr_requests
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.efr_requests.entrypoints=websecure"
      - "traefik.http.routers.efr_requests.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.efr_requests.service=efr_requests"
      - "traefik.http.services.efr_requests.loadbalancer.server.port=80"